package ru.softband.util.helpers

/**
  * date: 02.06.2016 23:00
  * author: Kaa
  *
  * Transliteration helper trait for Ru -> Translit text handling
  */
trait RuTransliterationHelper {
  val dictionary = Map(
    "А" -> "A",
    "Б" -> "B",
    "В" -> "V",
    "Г" -> "G",
    "Д" -> "D",
    "Е" -> "E",
    "Ё" -> "YO",
    "Ж" -> "ZH",
    "З" -> "Z",
    "И" -> "I",
    "Й" -> "Y",
    "К" -> "K",
    "Л" -> "L",
    "М" -> "M",
    "Н" -> "N",
    "О" -> "O",
    "П" -> "P",
    "Р" -> "R",
    "С" -> "S",
    "Т" -> "T",
    "У" -> "U",
    "Ф" -> "F",
    "Х" -> "H",
    "Ц" -> "TZ",
    "Ч" -> "CH",
    "Ш" -> "SH",
    "Щ" -> "SCH",
    "Ъ" -> "\'",
    "Ы" -> "Y",
    "Ь" -> "\'",
    "Э" -> "E",
    "Ю" -> "YU",
    "Я" -> "YA",
    "а" -> "a",
    "б" -> "b",
    "в" -> "v",
    "г" -> "g",
    "д" -> "d",
    "е" -> "e",
    "ё" -> "yo",
    "ж" -> "zh",
    "з" -> "z",
    "и" -> "i",
    "й" -> "y",
    "к" -> "k",
    "л" -> "l",
    "м" -> "m",
    "н" -> "n",
    "о" -> "o",
    "п" -> "p",
    "р" -> "r",
    "с" -> "s",
    "т" -> "t",
    "у" -> "u",
    "ф" -> "f",
    "х" -> "h",
    "ц" -> "tz",
    "ч" -> "ch",
    "ш" -> "sh",
    "щ" -> "sch",
    "ъ" -> "\'",
    "ы" -> "y",
    "ь" -> "\'",
    "э" -> "e",
    "ю" -> "yu",
    "я" -> "ya"
  )

  def transliterate(ruString: String) = ruString.foldLeft("")((s, c) => s + dictionary.getOrElse(c.toString, c.toString))
}
